### ISSUE TITLE
Error reported when running simple script.

### ISSUE THREAD

**Issue by nkolban** [101100/pca9685#5]
I am running on the May 10th 2016 build of Raspbian on a Pi3.  The JavaScript I am running is:

```
var i2cBus = require("i2c-bus");
var Pca9685Driver = require("pca9685").Pca9685Driver;

var options = {
    i2c: i2cBus.openSync(1),
    address: 0x40,
    frequency: 50,
    debug: true
};
pwm = new Pca9685Driver(options, function() {
    console.log("Initialization done");
});

pwm.setPulseLength(0, 1500);
```
I am running node.js version 4.4.4.

When I run the script, the error reported is:

```
$ sudo node test.js
  pca9685 Reseting PCA9685 +0ms
  pca9685 Setting PWM frequency to 50 Hz +16ms
  pca9685 Pre-scale value: 121 +8ms
  pca9685 Setting PWM channel, channel: 0, pulseLength: 1500, onStep: 0 +2ms
  pca9685 Setting PWM channel, channel: 0, onStep: 0, offStep: 306 +2ms
Error writing to PCA8685 via I2C { [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'writeByte' }
Error writing to PCA8685 via I2C { [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'writeByte' }
Error writing to PCA8685 via I2C { [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'writeByte' }
  pca9685 Error reading mode (to set frequency) +97ms { [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'readByte' }
Initialization done
  pca9685 Setting prescale to: 121 +2ms
Error writing to PCA8685 via I2C { [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'writeByte' }
Error writing to PCA8685 via I2C { [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'writeByte' }
Error writing to PCA8685 via I2C { [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'writeByte' }
Error writing to PCA8685 via I2C { [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'writeByte' }
/home/pi/projects/bubbles/node_modules/i2c-bus/i2c-bus.js:244
    i2c.writeByteAsync(device, cmd, byte, cb);
        ^

Error: EINVAL, incorrect arguments passed to writeByte(int fd, int cmd, int byte, function cb)
    at Error (native)
    at Bus.<anonymous> (/home/pi/projects/bubbles/node_modules/i2c-bus/i2c-bus.js:244:9)
    at Immediate.immediate._onImmediate (timers.js:440:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by nkolban** [comment]
Apologies ... a wire had become disconnected on the PCA9685 ... it wasn't visible as an I2C device.  Once plugged in, all worked.
